# Generated by Django 4.2.3 on 2023-07-30 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Когда создано объявление')),
                ('price', models.IntegerField(db_index=True, verbose_name='Цена торта')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий к заказу')),
                ('form', models.CharField(blank=True, max_length=50, verbose_name='Форма торта')),
                ('quantity_levels', models.IntegerField(db_index=True, verbose_name='Количество уровней торта')),
                ('topping', models.CharField(blank=True, max_length=50, verbose_name='Топпинг торта')),
                ('berries', models.CharField(blank=True, max_length=50, verbose_name='Ягоды в торте')),
                ('decor', models.CharField(blank=True, max_length=50, verbose_name='Декор торта')),
                ('inscription', models.CharField(blank=True, max_length=50, verbose_name='Надпись на  торт')),
                ('delivery_address', models.CharField(blank=True, max_length=100, verbose_name='Адрес доставки')),
                ('delivery_time', models.IntegerField(blank=True, max_length=100, verbose_name='Время доставки')),
            ],
        ),
    ]
