# Generated by Django 4.2.3 on 2023-07-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='delivery_time',
            field=models.IntegerField(db_index=True, verbose_name='Время доставки'),
        ),
    ]
