# Generated by Django 4.2.3 on 2023-07-31 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_cake_delivery_time_cake_delivery_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.CharField(db_index=True, max_length=200, verbose_name='Telegram компании')),
                ('instagram', models.CharField(db_index=True, max_length=200, verbose_name='Instagram компании')),
                ('phone_number', models.CharField(db_index=True, max_length=20, verbose_name='Номер компании')),
                ('address', models.CharField(db_index=True, max_length=200, verbose_name='Адрес компании')),
            ],
        ),
    ]
