# Generated by Django 4.2.3 on 2023-07-31 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_cake_delivery_address_alter_cake_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='image',
            field=models.ImageField(blank=True, upload_to='cake', verbose_name='Картинка'),
        ),
    ]
