# Generated by Django 4.2.3 on 2023-07-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cake_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Telegram компании'),
        ),
    ]
